name: Build Docker Images
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        base: [zookeeper, kafka]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: 'maven'

      - name: Build project
        run: mvn clean install -Pdocker -Ddocker.skip-test=true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.base }}
          file: ${{ matrix.base }}/Dockerfile.ubi8
          platforms: linux/amd64,linux/arm64
          push: false
          tags: ubi8-latest
          build-args: |
            ARTIFACT_ID=cp-${{ matrix.base }}-new
            PROJECT_VERSION=7.0.1