name: Build Docker Images
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: 'maven'

      - name: Build project
        run: mvn clean package -DskipTests -Pdocker -DCONFLUENT_PACKAGES_REPO='https://packages.confluent.io/rpm/7.0'   -DCONFLUENT_VERSION=7.0.0 -Ddocker.registry=nxt/


